export const SERVICES = [
  { 
    slug: "gbp-optimization",
    title: "Google Business Profile", 
    desc: "Get found on Google Maps and drive local customers.", 
    num: "01",
    longDesc: "Your Google Business Profile is the first thing local customers see. We don't just fill out your info—we optimize your listing so you show up at the top of Google Maps when people nearby are searching for your services.",
    benefits: ["Top 3 Google Maps Ranking", "More Phone Calls & Visits", "Managing Customer Reviews", "Local Search Dominance"],
    process: ["Profile Health Check", "Listing Optimization", "Regular Business Updates", "Photo & Video Management"],
    metric: "320%",
    metricLabel: "Increase in local phone leads",
    accentColor: "text-blue-400",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Local Map Dominance",
    featureDesc: "We use local search strategies to ensure your business is the first choice for customers in your neighborhood."
  },
  { 
    slug: "seo-strategy",
    title: "Search Engine Optimization (SEO)", 
    desc: "Grow your business with targeted traffic from Google.", 
    num: "02",
    longDesc: "We help your website show up on the first page of Google. By creating helpful content and fixing technical issues, we build a steady stream of new customers arriving at your site every single day without paying for ads.",
    benefits: ["Grow Free Website Traffic", "Lower Advertising Costs", "Attract Ready-to-Buy Customers", "Improve Website Speed & Health"],
    process: ["Website Health Check", "Keyword Research", "Content Optimization", "Building Online Authority"],
    metric: "12X",
    metricLabel: "Growth from free traffic",
    accentColor: "text-emerald-400",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426",
    featureTitle: "Long-Term Growth",
    featureDesc: "We focus on making your website the most trusted source in your industry so Google keeps sending you customers for years to come."
  },
  { 
    slug: "content-marketing",
    title: "Content Marketing", 
    desc: "Helpful articles that turn readers into customers.", 
    num: "03",
    longDesc: "Good content builds trust. We write high-quality articles, guides, and blog posts that answer your customers' questions and show them why you are the best choice for their needs.",
    benefits: ["Become an Industry Expert", "Educate Your Customers", "Build Brand Trust", "Boost Search Rankings"],
    process: ["Topic Research", "Professional Writing", "Sharing Across Platforms", "Results Tracking"],
    metric: "4.5M",
    metricLabel: "Monthly reading minutes accumulated",
    accentColor: "text-amber-400",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Building Authority",
    featureDesc: "We create a library of helpful information that educates your market and builds confidence in your business automatically."
  },
  { 
    slug: "social-media",
    title: "Social Media Management", 
    desc: "Build a loyal community on the platforms your customers love.", 
    num: "04",
    longDesc: "Social media is where your customers spend their time. We help you stay active, talk to your followers, and turn fans into loyal customers through consistent and engaging posts on platforms like Facebook and Instagram.",
    benefits: ["Direct Customer Contact", "Build Brand Loyalty", "Grow Your Following", "Get Real Feedback"],
    process: ["Identifying Your Audience", "Creating Engaging Posts", "Daily Account Management", "Measuring Growth"],
    metric: "85%",
    metricLabel: "Engagement rate lift",
    accentColor: "text-pink-400",
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=1974",
    featureTitle: "Active Community",
    featureDesc: "We don't just post content; we manage conversations that make your brand feel human and keep people coming back."
  },
  { 
    slug: "ppc-advertising",
    title: "Paid Advertising (PPC)", 
    desc: "Get instant results with targeted ads on Google and Social Media.", 
    num: "05",
    longDesc: "Paid ads are the fastest way to get new leads. We find exactly where your ideal customers are searching and show them the right ad at the right time to get you the best return on your investment.",
    benefits: ["Instant New Leads", "Predictable Results", "Quick Market Entry", "Tracking Every Dollar"],
    process: ["Customer Research", "Designing Great Ads", "Budget Management", "Scaling for Growth"],
    metric: "6.2",
    metricLabel: "Average return on ad spend",
    accentColor: "text-purple-400",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Efficiency First",
    featureDesc: "Our ad strategies and testing methods ensure every dollar you spend is working toward your sales goals.",
    platforms: [
      {
        name: "Google Ads",
        insight: "Be the first thing people see when they search for what you sell. We target high-intent customers ready to buy.",
        focus: ["Search Ads", "Google Shopping", "YouTube Campaigns"],
        color: "text-blue-400"
      },
      {
        name: "Meta Ads (FB/IG)",
        insight: "Reach thousands of potential customers based on their interests and behaviors on Facebook and Instagram.",
        focus: ["Direct Sales Ads", "Video Content", "Retargeting Lost Visitors"],
        color: "text-purple-400"
      },
      {
        name: "TikTok Ads",
        insight: "Reach a huge, active audience with fun and short videos that don't feel like boring traditional ads.",
        focus: ["Viral Social Ads", "Influencer Style", "Rapid Brand Growth"],
        color: "text-rose-400"
      }
    ]
  },
  { 
    slug: "ai-receptionist",
    title: "AI Receptionist & Chat Bot", 
    desc: "Answering customers and booking sales 24/7.", 
    num: "06",
    longDesc: "Never miss another lead. Our smart AI tools talk to your website visitors instantly, answer their common questions, and even book appointments for you while you're busy or sleeping.",
    benefits: ["24/7 Instant Response", "Never Miss a Lead", "Automatic Lead Filtering", "Easy CRM Integration"],
    process: ["Setting Up Knowledge", "Personality Styling", "System Testing", "Full Deployment"],
    metric: "98%",
    metricLabel: "Lead qualification accuracy",
    accentColor: "text-cyan-400",
    image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Smart Conversations",
    featureDesc: "Advanced AI allows our tools to handle complex questions and book meetings directly into your calendar without a human."
  },
  { 
    slug: "crm-integrations",
    title: "Sales & CRM Systems", 
    desc: "Organize your leads and automate your sales process.", 
    num: "07",
    longDesc: "Stop losing track of your leads. We set up easy-to-use systems that keep all your customer info in one place, automating follow-ups so you can close more sales with less effort.",
    benefits: ["See Your Sales Pipeline", "Automated Follow-Ups", "Better Business Decisions", "Increase Customer Value"],
    process: ["Workflow Mapping", "Data Organization", "Setting Up Automations", "Team Training"],
    metric: "45%",
    metricLabel: "Reduction in sales cycle time",
    accentColor: "text-indigo-400",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Smooth Sales Flow",
    featureDesc: "We remove the 'busy work' from your sales team by automating repetitive tasks and keeping your data clean."
  },
  { 
    slug: "global-branding",
    title: "Brand Identity & Design", 
    desc: "Create a professional look that customers trust.", 
    num: "08",
    longDesc: "In a world full of choices, looking professional is key. We craft a professional look and voice for your business that stands out from competitors and builds instant trust with your audience.",
    benefits: ["Stand Out from Others", "Premium Brand Look", "Connect with Customers", "Build Instant Authority"],
    process: ["Brand Discovery", "Logo & Visual Design", "Brand Guidelines", "Visual Launch"],
    metric: "2.5M",
    metricLabel: "Earned media impressions",
    accentColor: "text-rose-400",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "Professional Image",
    featureDesc: "We define the look and messaging that makes your brand the obvious choice in a crowded market."
  },
  { 
    slug: "marketing-funnel",
    title: "Marketing Funnel & Smart Sales System", 
    desc: "Custom paths that lead strangers to become customers.", 
    num: "09",
    longDesc: "Selling is a process. We build smart systems that guide potential customers from their first visit to the final purchase through automated and helpful steps that work 24/7.",
    benefits: ["Simple Customer Path", "Better Sales Results", "Automatic Follow-Ups", "Data-Driven Testing"],
    process: ["System Planning", "Content & Design", "Message Writing", "Launch & Growth"],
    metric: "310%",
    metricLabel: "Average lift in funnel conversion",
    accentColor: "text-blue-500",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2070",
    featureTitle: "The Growth Engine",
    featureDesc: "Our sales systems use real data to ensure the right message hits the right customer at the exact moment they are ready to buy."
  }
];
